AllCops:
  Exclude:
    - Gemfile
    - Gemfile.lock
    - 'bin/**/*'
    - 'db/**/*'
    - 'db/schema.rb'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'lib/tasks/**/*'

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/IndentationConsistency:
  AllowProtectedAndPrivateMethodsBeIndented: true
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Max: 140

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before

Style/EmptyMethod:
  EnforcedStyle: expanded